name: handy
description: A simple application for health tracking
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^6.0.1
  equatable: ^1.2.2
  intl: ^0.16.1
  http: ^0.12.2
  dio: ^3.0.9
  connectivity: ^0.4.9
  flutter_svg: ^0.17.4
  toast: ^0.1.5
  shared_preferences: ^0.5.8
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  responsive_x: ^0.0.5
  

  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Black.ttf
        - asset: assets/fonts/Rubik-BlackItalic.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik-BoldItalic.ttf
        - asset: assets/fonts/Rubik-Italic.ttf
        - asset: assets/fonts/Rubik-Light.ttf
        - asset: assets/fonts/Rubik-LightItalic.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-MediumItalic.ttf
        - asset: assets/fonts/Rubik-Regular.ttf
          style: normal
          weight: 900


